/**
 * Brand Configuration — Central config for the entire agentfront.
 * This file is auto-generated by the WWA Transform crawler.
 * All components import brand identity from here.
 */

export interface BrandStat {
  value: string;
  label: string;
}

export interface NavItem {
  label: string;
  page: string;
}

export interface BrandConfig {
  // Identity
  name: string;
  tagline: string;
  domain: string;
  logoSvg: string; // SVG string or empty for image-based logo
  logoImage: string; // Path to logo image (fallback)
  favicon: string;

  // Colors
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;

  // Navigation
  navItems: NavItem[];

  // Agent
  agentName: string;
  agentIdentity: string; // e.g. "a brand specialist"
  agentDeveloper: string; // e.g. "Iris Lab"

  // Stats (shown in hero)
  stats: BrandStat[];

  // Product terminology
  productLabel: string; // e.g. "Cards", "Plans", "Products"
  solutionLabel: string; // e.g. "Solutions", "Services", "Features"

  // Demo/CTA
  ctaPrimary: string; // e.g. "Book a Demo"
  ctaSecondary: string; // e.g. "Find a Card", "Get Started"

  // Social/links
  websiteUrl: string;

  // Deploy slug — MUST follow the pattern `project-<short-brand>-<4char-hex>`.
  // This is REQUIRED (Safe Browsing + collision avoidance — see SKILL.md Step 4.0).
  // Generate with: openssl rand -hex 2  →  project-book24-a4f2
  // The deployed URL is `https://wwa.${slug}.codiris.app`.
  // Never use the raw brand name as the slug for NEW transforms.
  slug: string; // e.g. "project-book24-a4f2"

  // MCP agent endpoint — served by /src/app/mcp/route.ts. Derived from slug.
  mcpUrl: string; // Public URL, e.g. "https://wwa.project-book24-a4f2.codiris.app/mcp"
  mcpServerName: string; // CLI identifier, e.g. "project-book24-a4f2-agent"
}

// ============================================================
// DEFAULT CONFIG — Replace with crawled data for each brand
// ============================================================
export const BRAND: BrandConfig = {
  name: "Brand",
  tagline: "Your tagline here",
  domain: "example.com",
  logoSvg: "",
  logoImage: "/images/brand-logo.png",
  favicon: "/favicon.ico",

  // Real hex values — these are written into the CSS custom properties
  // --color-brand-primary/secondary/accent by layout.tsx at runtime.
  // Every component reads the CSS var, not the raw hex, so changing these
  // three values propagates everywhere.
  primaryColor: "#1A1F71",
  secondaryColor: "#F7B600",
  accentColor: "#1434CB",

  navItems: [
    { label: "Products", page: "products" },
    { label: "Solutions", page: "solutions" },
    { label: "Pricing", page: "pricing" },
    { label: "Developers", page: "developers" },
    { label: "About", page: "about" },
  ],

  agentName: "AI Agent",
  agentIdentity: "a helpful specialist",
  agentDeveloper: "Iris Lab",

  stats: [
    { value: "100+", label: "Countries" },
    { value: "10M+", label: "Users" },
    { value: "99.9%", label: "Uptime" },
    { value: "24/7", label: "Support" },
  ],

  productLabel: "Products",
  solutionLabel: "Solutions",

  ctaPrimary: "Book a Demo",
  ctaSecondary: "Get Started",

  websiteUrl: "https://example.com",

  // REQUIRED: replace with your generated slug (see SKILL.md Step 4.0).
  // Pattern: project-<short-brand>-<4char-hex>
  slug: "project-brand-0000",
  mcpUrl: "https://wwa.project-brand-0000.codiris.app/mcp",
  mcpServerName: "project-brand-0000-agent",
};
