/**
 * Products/Cards — Auto-generated by WWA Transform crawler.
 * Represents purchasable items, plans, cards, or offerings.
 */

export interface ProductItem {
  id: string;
  name: string;
  issuer: string;
  tier: string;
  category: string;
  annualFee: string;
  apr: string;
  rewardRate: string;
  signUpBonus: string;
  image: string;
  features: string[];
  description: string;
  applyUrl: string;
}

// ============================================================
// PRODUCTS — Replace with crawled data
// ============================================================
export const productItems: ProductItem[] = [
  // Example:
  // {
  //   id: "plan-pro",
  //   name: "Pro Plan",
  //   issuer: "Brand",
  //   tier: "Professional",
  //   category: "Business",
  //   annualFee: "$99/yr",
  //   apr: "N/A",
  //   rewardRate: "Unlimited",
  //   signUpBonus: "Free trial",
  //   image: "/images/cards/pro-plan.png",
  //   features: ["Feature 1", "Feature 2", "Feature 3"],
  //   description: "Best for growing teams...",
  //   applyUrl: "#",
  // },
];
