/**
 * Solutions/Services — Auto-generated by WWA Transform crawler.
 * Each solution represents a product, service, or feature of the brand.
 */

export interface SolutionFeature {
  title: string;
  description: string;
}

export interface Solution {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  icon: string; // Lucide icon name
  image: string; // Hero image path
  features: SolutionFeature[];
  specs?: { label: string; value: string }[];
  relatedIds?: string[];
}

// ============================================================
// SOLUTIONS — Replace with crawled data
// ============================================================
export const solutions: Solution[] = [
  // Example:
  // {
  //   id: "product-1",
  //   name: "Product Name",
  //   tagline: "Short description",
  //   description: "Full description of the product...",
  //   category: "Payments",
  //   icon: "CreditCard",
  //   image: "/images/product-1.jpg",
  //   features: [
  //     { title: "Feature 1", description: "What it does" },
  //     { title: "Feature 2", description: "Another benefit" },
  //   ],
  // },
];
