import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { BrandData } from "./crawl";

const TEMPLATE_DIR = path.join(__dirname, "../../template");
const HOME = process.env.HOME || process.env.USERPROFILE || "~";

export async function generateProject(data: BrandData): Promise<string> {
  const projectDir = path.join(HOME, `wwa.${data.domain}`);

  // Step 1: Copy template
  console.log(`    Copying template to ${projectDir}...`);
  if (fs.existsSync(projectDir)) {
    console.log(`    Warning: ${projectDir} already exists. Overwriting brand files...`);
  } else {
    execSync(`cp -r "${TEMPLATE_DIR}" "${projectDir}"`, { stdio: "pipe" });
  }

  // Step 2: Write brand-config.ts
  const brandConfig = `/**
 * Brand Configuration — Auto-generated by WWA Transform
 * Source: https://${data.domain}
 */

export interface BrandStat { value: string; label: string; }
export interface NavItem { label: string; page: string; }
export interface BrandConfig {
  name: string; tagline: string; domain: string;
  logoSvg: string; logoImage: string; favicon: string;
  primaryColor: string; secondaryColor: string; accentColor: string;
  navItems: NavItem[]; agentName: string; agentIdentity: string; agentDeveloper: string;
  stats: BrandStat[]; productLabel: string; solutionLabel: string;
  ctaPrimary: string; ctaSecondary: string; websiteUrl: string;
}

export const BRAND: BrandConfig = {
  name: ${JSON.stringify(data.name)},
  tagline: ${JSON.stringify(data.tagline)},
  domain: ${JSON.stringify(data.domain)},
  logoSvg: "",
  logoImage: "/images/brand-logo.png",
  favicon: "/favicon.ico",
  primaryColor: ${JSON.stringify(data.primaryColor)},
  secondaryColor: ${JSON.stringify(data.secondaryColor)},
  accentColor: ${JSON.stringify(data.accentColor)},
  navItems: ${JSON.stringify(data.navItems.map(n => ({ label: n.label, page: n.page })), null, 4)},
  agentName: "${data.name} Agent",
  agentIdentity: "a ${data.name} specialist",
  agentDeveloper: "Iris Lab",
  stats: ${JSON.stringify(data.stats, null, 4)},
  productLabel: "Products",
  solutionLabel: "Solutions",
  ctaPrimary: "Book a Demo",
  ctaSecondary: "Get Started",
  websiteUrl: "https://${data.domain}",
};
`;
  fs.writeFileSync(path.join(projectDir, "src/lib/brand-config.ts"), brandConfig);

  // Step 3: Write solutions.ts
  const solutionsTs = `export interface SolutionFeature { title: string; description: string; }
export interface Solution {
  id: string; name: string; tagline: string; description: string;
  category: string; icon: string; image: string;
  features: SolutionFeature[]; specs?: { label: string; value: string }[];
  relatedIds?: string[];
}

export const solutions: Solution[] = ${JSON.stringify(data.solutions.map(s => ({
    ...s,
    image: `/images/${s.id}.jpg`,
    features: s.features.length > 0 ? s.features : [
      { title: "Key Feature", description: s.tagline },
    ],
  })), null, 2)};
`;
  fs.writeFileSync(path.join(projectDir, "src/lib/solutions.ts"), solutionsTs);

  // Step 4: Write cards.ts (empty if no products)
  const cardsTs = `export interface VisaCard {
  id: string; name: string; issuer: string; tier: string; category: string;
  annualFee: string; apr: string; rewardRate: string; signUpBonus: string;
  image: string; features: string[]; description: string; applyUrl: string;
}

export const visaCards: VisaCard[] = ${JSON.stringify(data.products, null, 2)};
`;
  fs.writeFileSync(path.join(projectDir, "src/lib/cards.ts"), cardsTs);

  // Step 5: Update layout.tsx metadata
  const layoutPath = path.join(projectDir, "src/app/layout.tsx");
  if (fs.existsSync(layoutPath)) {
    let layout = fs.readFileSync(layoutPath, "utf-8");
    layout = layout.replace(/title: "[^"]*"/, `title: "${data.name} — WWA Agentfront"`);
    layout = layout.replace(/description: "[^"]*"/, `description: "${data.tagline}"`);
    fs.writeFileSync(layoutPath, layout);
  }

  // Step 6: Update globals.css with brand colors
  const cssPath = path.join(projectDir, "src/app/globals.css");
  if (fs.existsSync(cssPath)) {
    let css = fs.readFileSync(cssPath, "utf-8");
    // Add brand color variables at the top
    const colorVars = `\n:root {\n  --brand-primary: ${data.primaryColor};\n  --brand-secondary: ${data.secondaryColor};\n  --brand-accent: ${data.accentColor};\n}\n`;
    css = colorVars + css;
    fs.writeFileSync(cssPath, css);
  }

  // Step 7: Install dependencies
  console.log(`    Installing dependencies...`);
  try {
    execSync("npm install", { cwd: projectDir, stdio: "pipe" });
  } catch {
    console.log("    Warning: npm install had issues. You may need to run it manually.");
  }

  return projectDir;
}
